### ISSUE TITLE
Mesh normals

### ISSUE THREAD

**Issue by seghier** [torinos-yt/VL.Alembic#5]
Hello
How to get normals from meshes?

**Comment by torinos-yt** [comment]
As shown in #3, if the normal information is included, you should be able to get the normal of each vertex from the Buffer obtained by GetMeshes() in the order of Pos(12bytes),Normal(12bytes),UV(8bytes), and then in the same order for the next vertex.

If you are using Blender, geometry consisting of only smooth faces will be exported without normal information, so you will need to create a custom normal by using the NormalEdit modifier with mixFactor set to 0, etc.

Close the issue once, but feel free to reopen it if not resolved.
